// Generated by roo_pbc 0.1.0. Do not edit.
#pragma once

#include "roo_pb/message.h"

namespace roo::comms {

/// Schema enum; proto3 permits unknown numeric values.
enum class RealmId : int32_t {
  kUnspecifiedRealm = 0,
  kHomeAutomation = 1,
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class DeviceDescriptor {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 142;

  /// Creates a message initialized to schema defaults.
  DeviceDescriptor() {}

  /// Returns the current field value or its schema default.
  const int64_t& realm_id() const { return realm_id_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_realm_id(int64_t value) { realm_id_ = value; }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_realm_id() { realm_id_ = 0; }

  /// Returns the current field value or its schema default.
  const ::roo_pb::BoundedString<128>& payload() const { return payload_; }

  /// Assigns bytes without changing the field on capacity failure.
  bool try_set_payload(const char* value, size_t size) {
    ::roo_pb::BoundedString<128> temporary;
    if (!temporary.assign(value, size)) return false;
    payload_ = std::move(temporary);
    return true;
  }

  /// Assigns a NUL-terminated string, reporting capacity failure.
  bool try_set_payload(const char* value) {
    return value != nullptr && try_set_payload(value, std::strlen(value));
  }

  /// Assigns bytes; capacity is a release-checked precondition.
  void set_payload(const char* value, size_t size) {
    ::roo_pb::Require(try_set_payload(value, size));
  }

  /// Assigns a NUL-terminated string with checked capacity.
  void set_payload(const char* value) {
    ::roo_pb::Require(try_set_payload(value));
  }

  /// Marks the field present and returns mutable owned storage.
  ::roo_pb::BoundedString<128>* mutable_payload() { return &payload_; }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_payload() { payload_.clear(); }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() {
    clear_realm_id();
    clear_payload();
  }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const { return true; }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kInt64)) {
            input.skip(tag);
            break;
          }
          int64_t item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kInt64>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_realm_id(item);
          break;
        }
        case 2: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kBytes)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kBytes>(input, payload_);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (!payload_.empty())
      ::roo_pb::WriteField<::roo_pb::Kind::kBytes>(output, 2, payload_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (realm_id_ != 0)
      ::roo_pb::WriteField<::roo_pb::Kind::kInt64>(output, 1, realm_id_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  int64_t realm_id_{0};
  ::roo_pb::BoundedString<128> payload_{};
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class HomeAutomationDeviceDescriptor_EnvironmentalSensor {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 4;

  /// Creates a message initialized to schema defaults.
  HomeAutomationDeviceDescriptor_EnvironmentalSensor() {}

  /// Returns the current field value or its schema default.
  const bool& has_aht20() const { return has_aht20_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_has_aht20(bool value) { has_aht20_ = value; }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_has_aht20() { has_aht20_ = false; }

  /// Returns the current field value or its schema default.
  const bool& has_bmp280() const { return has_bmp280_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_has_bmp280(bool value) { has_bmp280_ = value; }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_has_bmp280() { has_bmp280_ = false; }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() {
    clear_has_aht20();
    clear_has_bmp280();
  }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const { return true; }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kBool)) {
            input.skip(tag);
            break;
          }
          bool item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kBool>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_has_aht20(item);
          break;
        }
        case 2: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kBool)) {
            input.skip(tag);
            break;
          }
          bool item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kBool>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_has_bmp280(item);
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_bmp280_ != false)
      ::roo_pb::WriteField<::roo_pb::Kind::kBool>(output, 2, has_bmp280_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_aht20_ != false)
      ::roo_pb::WriteField<::roo_pb::Kind::kBool>(output, 1, has_aht20_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  bool has_aht20_{false};
  bool has_bmp280_{false};
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class HomeAutomationDeviceDescriptor_Relay {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 11;

  /// Creates a message initialized to schema defaults.
  HomeAutomationDeviceDescriptor_Relay() {}

  /// Returns the current field value or its schema default.
  const int32_t& port_count() const { return port_count_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_port_count(int32_t value) { port_count_ = value; }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_port_count() { port_count_ = 0; }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() { clear_port_count(); }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const { return true; }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kInt32)) {
            input.skip(tag);
            break;
          }
          int32_t item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kInt32>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_port_count(item);
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (port_count_ != 0)
      ::roo_pb::WriteField<::roo_pb::Kind::kInt32>(output, 1, port_count_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  int32_t port_count_{0};
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class HomeAutomationDeviceDescriptor {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 19;

  using EnvironmentalSensor =
      ::roo::comms::HomeAutomationDeviceDescriptor_EnvironmentalSensor;
  using Relay = ::roo::comms::HomeAutomationDeviceDescriptor_Relay;

  /// Creates a message initialized to schema defaults.
  HomeAutomationDeviceDescriptor() {}

  /// Destroys active oneof values and their owned resources.
  ~HomeAutomationDeviceDescriptor() { clear_kind(); }

  /// Copies owned values and borrowed callback bindings from @p other.
  HomeAutomationDeviceDescriptor(const HomeAutomationDeviceDescriptor& other)
      : HomeAutomationDeviceDescriptor() {
    *this = other;
  }

  /// Copies values and bindings; self-assignment leaves the message unchanged.
  HomeAutomationDeviceDescriptor& operator=(
      const HomeAutomationDeviceDescriptor& other) {
    if (this == &other) return *this;
    clear_kind();
    switch (other.kind_case_) {
      case 1:
        ::new (static_cast<void*>(&environmental_sensor_))::roo::comms::
            HomeAutomationDeviceDescriptor_EnvironmentalSensor(
                other.environmental_sensor_);
        break;
      case 2:
        ::new (static_cast<void*>(&relay_))::roo::comms::
            HomeAutomationDeviceDescriptor_Relay(other.relay_);
        break;
      default:
        break;
    }
    kind_case_ = other.kind_case_;
    return *this;
  }

  /// Moves owned values and borrowed callback bindings from @p other.
  HomeAutomationDeviceDescriptor(
      HomeAutomationDeviceDescriptor&& other) noexcept
      : HomeAutomationDeviceDescriptor() {
    *this = std::move(other);
  }

  /// Moves values and bindings; self-assignment leaves the message unchanged.
  HomeAutomationDeviceDescriptor& operator=(
      HomeAutomationDeviceDescriptor&& other) noexcept {
    if (this == &other) return *this;
    clear_kind();
    switch (other.kind_case_) {
      case 1:
        ::new (static_cast<void*>(&environmental_sensor_))::roo::comms::
            HomeAutomationDeviceDescriptor_EnvironmentalSensor(
                std::move(other.environmental_sensor_));
        break;
      case 2:
        ::new (static_cast<void*>(&relay_))::roo::comms::
            HomeAutomationDeviceDescriptor_Relay(std::move(other.relay_));
        break;
      default:
        break;
    }
    kind_case_ = other.kind_case_;
    return *this;
  }

  /// Identifies the active alternative in kind.
  enum class KindCase : uint32_t {
    kNotSet = 0,
    kEnvironmentalSensor = 1,
    kRelay = 2,
  };

  /// Returns the active oneof alternative.
  KindCase kind_case() const { return static_cast<KindCase>(kind_case_); }

  /// Destroys the active value and clears selection; callback bindings survive.
  void clear_kind() {
    switch (kind_case_) {
      case 1: {
        using Value =
            ::roo::comms::HomeAutomationDeviceDescriptor_EnvironmentalSensor;
        environmental_sensor_.~Value();
        break;
      }
      case 2: {
        using Value = ::roo::comms::HomeAutomationDeviceDescriptor_Relay;
        relay_.~Value();
        break;
      }
      default:
        break;
    }
    kind_case_ = 0;
  }

  /// Returns the current field value or its schema default.
  const ::roo::comms::HomeAutomationDeviceDescriptor_EnvironmentalSensor&
  environmental_sensor() const {
    if (has_environmental_sensor()) return environmental_sensor_;
    static const ::roo::comms::
        HomeAutomationDeviceDescriptor_EnvironmentalSensor default_value{};
    return default_value;
  }

  /// Reports explicit field presence.
  bool has_environmental_sensor() const { return kind_case_ == 1; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::HomeAutomationDeviceDescriptor_EnvironmentalSensor*
  mutable_environmental_sensor() {
    if (kind_case_ != 1) {
      clear_kind();
      ::new (static_cast<void*>(&environmental_sensor_))::roo::comms::
          HomeAutomationDeviceDescriptor_EnvironmentalSensor{};
      kind_case_ = 1;
    }
    return &environmental_sensor_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_environmental_sensor() {
    if (has_environmental_sensor()) clear_kind();
  }

  /// Returns the current field value or its schema default.
  const ::roo::comms::HomeAutomationDeviceDescriptor_Relay& relay() const {
    if (has_relay()) return relay_;
    static const ::roo::comms::HomeAutomationDeviceDescriptor_Relay
        default_value{};
    return default_value;
  }

  /// Reports explicit field presence.
  bool has_relay() const { return kind_case_ == 2; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::HomeAutomationDeviceDescriptor_Relay* mutable_relay() {
    if (kind_case_ != 2) {
      clear_kind();
      ::new (static_cast<void*>(
          &relay_))::roo::comms::HomeAutomationDeviceDescriptor_Relay{};
      kind_case_ = 2;
    }
    return &relay_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_relay() {
    if (has_relay()) clear_kind();
  }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() { clear_kind(); }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const {
    if (has_environmental_sensor() && !environmental_sensor_.IsInitialized())
      return false;
    if (has_relay() && !relay_.IsInitialized()) return false;
    return true;
  }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(
              input, *mutable_environmental_sensor());
          break;
        }
        case 2: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(input,
                                                        *mutable_relay());
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_relay())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 2, relay_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_environmental_sensor())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 1,
                                                     environmental_sensor_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  uint32_t kind_case_ = 0;
  // Only the selected alternative has a live object in this storage.
  union {
    ::roo::comms::HomeAutomationDeviceDescriptor_EnvironmentalSensor
        environmental_sensor_;
    ::roo::comms::HomeAutomationDeviceDescriptor_Relay relay_;
  };
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class ControlMessage_HubDiscoveryRequest {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 145;

  /// Creates a message initialized to schema defaults.
  ControlMessage_HubDiscoveryRequest() : has_device_descriptor_(0) {}

  /// Returns the current field value or its schema default.
  const ::roo::comms::DeviceDescriptor& device_descriptor() const {
    return device_descriptor_;
  }

  /// Reports explicit field presence.
  bool has_device_descriptor() const { return has_device_descriptor_; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::DeviceDescriptor* mutable_device_descriptor() {
    has_device_descriptor_ = true;
    return &device_descriptor_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_device_descriptor() {
    device_descriptor_.Clear();
    has_device_descriptor_ = false;
  }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() { clear_device_descriptor(); }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const {
    if (has_device_descriptor() && !device_descriptor_.IsInitialized())
      return false;
    return true;
  }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(
              input, *mutable_device_descriptor());
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_device_descriptor())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 1,
                                                     device_descriptor_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  ::roo::comms::DeviceDescriptor device_descriptor_{};
  // Grouped presence bits; oneof presence uses its case discriminator.
  uint8_t has_device_descriptor_ : 1;
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class ControlMessage_HubDiscoveryResponse {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 6;

  /// Creates a message initialized to schema defaults.
  ControlMessage_HubDiscoveryResponse() {}

  /// Returns the current field value or its schema default.
  const uint32_t& hub_channel() const { return hub_channel_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_hub_channel(uint32_t value) { hub_channel_ = value; }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_hub_channel() { hub_channel_ = 0; }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() { clear_hub_channel(); }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const { return true; }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kUint32)) {
            input.skip(tag);
            break;
          }
          uint32_t item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kUint32>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_hub_channel(item);
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (hub_channel_ != 0)
      ::roo_pb::WriteField<::roo_pb::Kind::kUint32>(output, 1, hub_channel_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  uint32_t hub_channel_{0};
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class ControlMessage_HubPairingRequest {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 145;

  /// Creates a message initialized to schema defaults.
  ControlMessage_HubPairingRequest() : has_device_descriptor_(0) {}

  /// Returns the current field value or its schema default.
  const ::roo::comms::DeviceDescriptor& device_descriptor() const {
    return device_descriptor_;
  }

  /// Reports explicit field presence.
  bool has_device_descriptor() const { return has_device_descriptor_; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::DeviceDescriptor* mutable_device_descriptor() {
    has_device_descriptor_ = true;
    return &device_descriptor_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_device_descriptor() {
    device_descriptor_.Clear();
    has_device_descriptor_ = false;
  }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() { clear_device_descriptor(); }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const {
    if (has_device_descriptor() && !device_descriptor_.IsInitialized())
      return false;
    return true;
  }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(
              input, *mutable_device_descriptor());
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_device_descriptor())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 1,
                                                     device_descriptor_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  ::roo::comms::DeviceDescriptor device_descriptor_{};
  // Grouped presence bits; oneof presence uses its case discriminator.
  uint8_t has_device_descriptor_ : 1;
};

/// Schema enum; proto3 permits unknown numeric values.
enum class ControlMessage_HubPairingResponse_Status : int32_t {
  kOk = 0,
  kRejected = 1,
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class ControlMessage_HubPairingResponse {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 11;

  using Status = ::roo::comms::ControlMessage_HubPairingResponse_Status;

  /// Creates a message initialized to schema defaults.
  ControlMessage_HubPairingResponse() {}

  /// Returns the current field value or its schema default.
  const ::roo::comms::ControlMessage_HubPairingResponse_Status& status() const {
    return status_;
  }

  /// Assigns the field and updates explicit presence when applicable.
  void set_status(
      ::roo::comms::ControlMessage_HubPairingResponse_Status value) {
    status_ = value;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_status() {
    status_ = ::roo::comms::ControlMessage_HubPairingResponse_Status::kOk;
  }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() { clear_status(); }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const { return true; }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kEnum)) {
            input.skip(tag);
            break;
          }
          ::roo::comms::ControlMessage_HubPairingResponse_Status item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kEnum>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_status(item);
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (status_ != ::roo::comms::ControlMessage_HubPairingResponse_Status::kOk)
      ::roo_pb::WriteField<::roo_pb::Kind::kEnum>(output, 1, status_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  ::roo::comms::ControlMessage_HubPairingResponse_Status status_{
      ::roo::comms::ControlMessage_HubPairingResponse_Status::kOk};
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class ControlMessage {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 317;

  using HubDiscoveryRequest = ::roo::comms::ControlMessage_HubDiscoveryRequest;
  using HubDiscoveryResponse =
      ::roo::comms::ControlMessage_HubDiscoveryResponse;
  using HubPairingRequest = ::roo::comms::ControlMessage_HubPairingRequest;
  using HubPairingResponse = ::roo::comms::ControlMessage_HubPairingResponse;

  /// Creates a message initialized to schema defaults.
  ControlMessage() {}

  /// Destroys active oneof values and their owned resources.
  ~ControlMessage() { clear_contents(); }

  /// Copies owned values and borrowed callback bindings from @p other.
  ControlMessage(const ControlMessage& other) : ControlMessage() {
    *this = other;
  }

  /// Copies values and bindings; self-assignment leaves the message unchanged.
  ControlMessage& operator=(const ControlMessage& other) {
    if (this == &other) return *this;
    clear_contents();
    switch (other.contents_case_) {
      case 1:
        ::new (static_cast<void*>(&hub_discovery_request_))::roo::comms::
            ControlMessage_HubDiscoveryRequest(other.hub_discovery_request_);
        break;
      case 2:
        ::new (static_cast<void*>(&hub_discovery_response_))::roo::comms::
            ControlMessage_HubDiscoveryResponse(other.hub_discovery_response_);
        break;
      case 3:
        ::new (static_cast<void*>(&hub_pairing_request_))::roo::comms::
            ControlMessage_HubPairingRequest(other.hub_pairing_request_);
        break;
      case 4:
        ::new (static_cast<void*>(&hub_pairing_response_))::roo::comms::
            ControlMessage_HubPairingResponse(other.hub_pairing_response_);
        break;
      default:
        break;
    }
    contents_case_ = other.contents_case_;
    return *this;
  }

  /// Moves owned values and borrowed callback bindings from @p other.
  ControlMessage(ControlMessage&& other) noexcept : ControlMessage() {
    *this = std::move(other);
  }

  /// Moves values and bindings; self-assignment leaves the message unchanged.
  ControlMessage& operator=(ControlMessage&& other) noexcept {
    if (this == &other) return *this;
    clear_contents();
    switch (other.contents_case_) {
      case 1:
        ::new (static_cast<void*>(&hub_discovery_request_))::roo::comms::
            ControlMessage_HubDiscoveryRequest(
                std::move(other.hub_discovery_request_));
        break;
      case 2:
        ::new (static_cast<void*>(&hub_discovery_response_))::roo::comms::
            ControlMessage_HubDiscoveryResponse(
                std::move(other.hub_discovery_response_));
        break;
      case 3:
        ::new (static_cast<void*>(&hub_pairing_request_))::roo::comms::
            ControlMessage_HubPairingRequest(
                std::move(other.hub_pairing_request_));
        break;
      case 4:
        ::new (static_cast<void*>(&hub_pairing_response_))::roo::comms::
            ControlMessage_HubPairingResponse(
                std::move(other.hub_pairing_response_));
        break;
      default:
        break;
    }
    contents_case_ = other.contents_case_;
    return *this;
  }

  /// Identifies the active alternative in contents.
  enum class ContentsCase : uint32_t {
    kNotSet = 0,
    kHubDiscoveryRequest = 1,
    kHubDiscoveryResponse = 2,
    kHubPairingRequest = 3,
    kHubPairingResponse = 4,
  };

  /// Returns the active oneof alternative.
  ContentsCase contents_case() const {
    return static_cast<ContentsCase>(contents_case_);
  }

  /// Destroys the active value and clears selection; callback bindings survive.
  void clear_contents() {
    switch (contents_case_) {
      case 1: {
        using Value = ::roo::comms::ControlMessage_HubDiscoveryRequest;
        hub_discovery_request_.~Value();
        break;
      }
      case 2: {
        using Value = ::roo::comms::ControlMessage_HubDiscoveryResponse;
        hub_discovery_response_.~Value();
        break;
      }
      case 3: {
        using Value = ::roo::comms::ControlMessage_HubPairingRequest;
        hub_pairing_request_.~Value();
        break;
      }
      case 4: {
        using Value = ::roo::comms::ControlMessage_HubPairingResponse;
        hub_pairing_response_.~Value();
        break;
      }
      default:
        break;
    }
    contents_case_ = 0;
  }

  /// Returns the current field value or its schema default.
  const ::roo::comms::ControlMessage_HubDiscoveryRequest&
  hub_discovery_request() const {
    if (has_hub_discovery_request()) return hub_discovery_request_;
    static const ::roo::comms::ControlMessage_HubDiscoveryRequest
        default_value{};
    return default_value;
  }

  /// Reports explicit field presence.
  bool has_hub_discovery_request() const { return contents_case_ == 1; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::ControlMessage_HubDiscoveryRequest*
  mutable_hub_discovery_request() {
    if (contents_case_ != 1) {
      clear_contents();
      ::new (static_cast<void*>(&hub_discovery_request_))::roo::comms::
          ControlMessage_HubDiscoveryRequest{};
      contents_case_ = 1;
    }
    return &hub_discovery_request_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_hub_discovery_request() {
    if (has_hub_discovery_request()) clear_contents();
  }

  /// Returns the current field value or its schema default.
  const ::roo::comms::ControlMessage_HubDiscoveryResponse&
  hub_discovery_response() const {
    if (has_hub_discovery_response()) return hub_discovery_response_;
    static const ::roo::comms::ControlMessage_HubDiscoveryResponse
        default_value{};
    return default_value;
  }

  /// Reports explicit field presence.
  bool has_hub_discovery_response() const { return contents_case_ == 2; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::ControlMessage_HubDiscoveryResponse*
  mutable_hub_discovery_response() {
    if (contents_case_ != 2) {
      clear_contents();
      ::new (static_cast<void*>(&hub_discovery_response_))::roo::comms::
          ControlMessage_HubDiscoveryResponse{};
      contents_case_ = 2;
    }
    return &hub_discovery_response_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_hub_discovery_response() {
    if (has_hub_discovery_response()) clear_contents();
  }

  /// Returns the current field value or its schema default.
  const ::roo::comms::ControlMessage_HubPairingRequest& hub_pairing_request()
      const {
    if (has_hub_pairing_request()) return hub_pairing_request_;
    static const ::roo::comms::ControlMessage_HubPairingRequest default_value{};
    return default_value;
  }

  /// Reports explicit field presence.
  bool has_hub_pairing_request() const { return contents_case_ == 3; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::ControlMessage_HubPairingRequest*
  mutable_hub_pairing_request() {
    if (contents_case_ != 3) {
      clear_contents();
      ::new (static_cast<void*>(&hub_pairing_request_))::roo::comms::
          ControlMessage_HubPairingRequest{};
      contents_case_ = 3;
    }
    return &hub_pairing_request_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_hub_pairing_request() {
    if (has_hub_pairing_request()) clear_contents();
  }

  /// Returns the current field value or its schema default.
  const ::roo::comms::ControlMessage_HubPairingResponse& hub_pairing_response()
      const {
    if (has_hub_pairing_response()) return hub_pairing_response_;
    static const ::roo::comms::ControlMessage_HubPairingResponse
        default_value{};
    return default_value;
  }

  /// Reports explicit field presence.
  bool has_hub_pairing_response() const { return contents_case_ == 4; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::ControlMessage_HubPairingResponse*
  mutable_hub_pairing_response() {
    if (contents_case_ != 4) {
      clear_contents();
      ::new (static_cast<void*>(&hub_pairing_response_))::roo::comms::
          ControlMessage_HubPairingResponse{};
      contents_case_ = 4;
    }
    return &hub_pairing_response_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_hub_pairing_response() {
    if (has_hub_pairing_response()) clear_contents();
  }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() { clear_contents(); }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const {
    if (has_hub_discovery_request() && !hub_discovery_request_.IsInitialized())
      return false;
    if (has_hub_discovery_response() &&
        !hub_discovery_response_.IsInitialized())
      return false;
    if (has_hub_pairing_request() && !hub_pairing_request_.IsInitialized())
      return false;
    if (has_hub_pairing_response() && !hub_pairing_response_.IsInitialized())
      return false;
    return true;
  }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(
              input, *mutable_hub_discovery_request());
          break;
        }
        case 2: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(
              input, *mutable_hub_discovery_response());
          break;
        }
        case 3: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(
              input, *mutable_hub_pairing_request());
          break;
        }
        case 4: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(
              input, *mutable_hub_pairing_response());
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_hub_pairing_response())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 4,
                                                     hub_pairing_response_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_hub_pairing_request())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 3,
                                                     hub_pairing_request_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_hub_discovery_response())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 2,
                                                     hub_discovery_response_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_hub_discovery_request())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 1,
                                                     hub_discovery_request_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  uint32_t contents_case_ = 0;
  // Only the selected alternative has a live object in this storage.
  union {
    ::roo::comms::ControlMessage_HubDiscoveryRequest hub_discovery_request_;
    ::roo::comms::ControlMessage_HubDiscoveryResponse hub_discovery_response_;
    ::roo::comms::ControlMessage_HubPairingRequest hub_pairing_request_;
    ::roo::comms::ControlMessage_HubPairingResponse hub_pairing_response_;
  };
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class DataMessage_EnvironmentalSensorReadings_AHT20 {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 10;

  /// Creates a message initialized to schema defaults.
  DataMessage_EnvironmentalSensorReadings_AHT20()
      : has_temperature_celsius_(0), has_humidity_percent_(0) {}

  /// Returns the current field value or its schema default.
  const float& temperature_celsius() const { return temperature_celsius_; }

  /// Reports explicit field presence.
  bool has_temperature_celsius() const { return has_temperature_celsius_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_temperature_celsius(float value) {
    has_temperature_celsius_ = true;
    temperature_celsius_ = value;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_temperature_celsius() {
    temperature_celsius_ = static_cast<float>(0);
    has_temperature_celsius_ = false;
  }

  /// Returns the current field value or its schema default.
  const float& humidity_percent() const { return humidity_percent_; }

  /// Reports explicit field presence.
  bool has_humidity_percent() const { return has_humidity_percent_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_humidity_percent(float value) {
    has_humidity_percent_ = true;
    humidity_percent_ = value;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_humidity_percent() {
    humidity_percent_ = static_cast<float>(0);
    has_humidity_percent_ = false;
  }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() {
    clear_temperature_celsius();
    clear_humidity_percent();
  }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const { return true; }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kFloat)) {
            input.skip(tag);
            break;
          }
          float item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kFloat>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_temperature_celsius(item);
          break;
        }
        case 2: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kFloat)) {
            input.skip(tag);
            break;
          }
          float item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kFloat>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_humidity_percent(item);
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_humidity_percent())
      ::roo_pb::WriteField<::roo_pb::Kind::kFloat>(output, 2,
                                                   humidity_percent_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_temperature_celsius())
      ::roo_pb::WriteField<::roo_pb::Kind::kFloat>(output, 1,
                                                   temperature_celsius_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  float temperature_celsius_{static_cast<float>(0)};
  float humidity_percent_{static_cast<float>(0)};
  // Grouped presence bits; oneof presence uses its case discriminator.
  uint8_t has_temperature_celsius_ : 1;
  uint8_t has_humidity_percent_ : 1;
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class DataMessage_EnvironmentalSensorReadings_BMP280 {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 10;

  /// Creates a message initialized to schema defaults.
  DataMessage_EnvironmentalSensorReadings_BMP280()
      : has_temperature_celsius_(0), has_pressure_pa_(0) {}

  /// Returns the current field value or its schema default.
  const float& temperature_celsius() const { return temperature_celsius_; }

  /// Reports explicit field presence.
  bool has_temperature_celsius() const { return has_temperature_celsius_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_temperature_celsius(float value) {
    has_temperature_celsius_ = true;
    temperature_celsius_ = value;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_temperature_celsius() {
    temperature_celsius_ = static_cast<float>(0);
    has_temperature_celsius_ = false;
  }

  /// Returns the current field value or its schema default.
  const float& pressure_pa() const { return pressure_pa_; }

  /// Reports explicit field presence.
  bool has_pressure_pa() const { return has_pressure_pa_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_pressure_pa(float value) {
    has_pressure_pa_ = true;
    pressure_pa_ = value;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_pressure_pa() {
    pressure_pa_ = static_cast<float>(0);
    has_pressure_pa_ = false;
  }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() {
    clear_temperature_celsius();
    clear_pressure_pa();
  }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const { return true; }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kFloat)) {
            input.skip(tag);
            break;
          }
          float item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kFloat>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_temperature_celsius(item);
          break;
        }
        case 2: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kFloat)) {
            input.skip(tag);
            break;
          }
          float item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kFloat>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_pressure_pa(item);
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_pressure_pa())
      ::roo_pb::WriteField<::roo_pb::Kind::kFloat>(output, 2, pressure_pa_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_temperature_celsius())
      ::roo_pb::WriteField<::roo_pb::Kind::kFloat>(output, 1,
                                                   temperature_celsius_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  float temperature_celsius_{static_cast<float>(0)};
  float pressure_pa_{static_cast<float>(0)};
  // Grouped presence bits; oneof presence uses its case discriminator.
  uint8_t has_temperature_celsius_ : 1;
  uint8_t has_pressure_pa_ : 1;
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class DataMessage_EnvironmentalSensorReadings {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 29;

  using AHT20 = ::roo::comms::DataMessage_EnvironmentalSensorReadings_AHT20;
  using BMP280 = ::roo::comms::DataMessage_EnvironmentalSensorReadings_BMP280;

  /// Creates a message initialized to schema defaults.
  DataMessage_EnvironmentalSensorReadings()
      : has_generic_temperature_celcius_(0), has_aht20_(0), has_bmp280_(0) {}

  /// Returns the current field value or its schema default.
  const float& generic_temperature_celcius() const {
    return generic_temperature_celcius_;
  }

  /// Reports explicit field presence.
  bool has_generic_temperature_celcius() const {
    return has_generic_temperature_celcius_;
  }

  /// Assigns the field and updates explicit presence when applicable.
  void set_generic_temperature_celcius(float value) {
    has_generic_temperature_celcius_ = true;
    generic_temperature_celcius_ = value;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_generic_temperature_celcius() {
    generic_temperature_celcius_ = static_cast<float>(0);
    has_generic_temperature_celcius_ = false;
  }

  /// Returns the current field value or its schema default.
  const ::roo::comms::DataMessage_EnvironmentalSensorReadings_AHT20& aht20()
      const {
    return aht20_;
  }

  /// Reports explicit field presence.
  bool has_aht20() const { return has_aht20_; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::DataMessage_EnvironmentalSensorReadings_AHT20* mutable_aht20() {
    has_aht20_ = true;
    return &aht20_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_aht20() {
    aht20_.Clear();
    has_aht20_ = false;
  }

  /// Returns the current field value or its schema default.
  const ::roo::comms::DataMessage_EnvironmentalSensorReadings_BMP280& bmp280()
      const {
    return bmp280_;
  }

  /// Reports explicit field presence.
  bool has_bmp280() const { return has_bmp280_; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::DataMessage_EnvironmentalSensorReadings_BMP280*
  mutable_bmp280() {
    has_bmp280_ = true;
    return &bmp280_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_bmp280() {
    bmp280_.Clear();
    has_bmp280_ = false;
  }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() {
    clear_generic_temperature_celcius();
    clear_aht20();
    clear_bmp280();
  }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const {
    if (has_aht20() && !aht20_.IsInitialized()) return false;
    if (has_bmp280() && !bmp280_.IsInitialized()) return false;
    return true;
  }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kFloat)) {
            input.skip(tag);
            break;
          }
          float item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kFloat>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_generic_temperature_celcius(item);
          break;
        }
        case 2: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(input,
                                                        *mutable_aht20());
          break;
        }
        case 3: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(input,
                                                        *mutable_bmp280());
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_bmp280())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 3, bmp280_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_aht20())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 2, aht20_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_generic_temperature_celcius())
      ::roo_pb::WriteField<::roo_pb::Kind::kFloat>(
          output, 1, generic_temperature_celcius_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  float generic_temperature_celcius_{static_cast<float>(0)};
  ::roo::comms::DataMessage_EnvironmentalSensorReadings_AHT20 aht20_{};
  ::roo::comms::DataMessage_EnvironmentalSensorReadings_BMP280 bmp280_{};
  // Grouped presence bits; oneof presence uses its case discriminator.
  uint8_t has_generic_temperature_celcius_ : 1;
  uint8_t has_aht20_ : 1;
  uint8_t has_bmp280_ : 1;
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class DataMessage_RelayRequest {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 10;

  /// Creates a message initialized to schema defaults.
  DataMessage_RelayRequest() {}

  /// Returns the current field value or its schema default.
  const uint32_t& mask() const { return mask_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_mask(uint32_t value) { mask_ = value; }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_mask() { mask_ = 0; }

  /// Returns the current field value or its schema default.
  const uint32_t& write() const { return write_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_write(uint32_t value) { write_ = value; }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_write() { write_ = 0; }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() {
    clear_mask();
    clear_write();
  }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const { return true; }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kFixed32)) {
            input.skip(tag);
            break;
          }
          uint32_t item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kFixed32>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_mask(item);
          break;
        }
        case 2: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kFixed32)) {
            input.skip(tag);
            break;
          }
          uint32_t item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kFixed32>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_write(item);
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (write_ != 0)
      ::roo_pb::WriteField<::roo_pb::Kind::kFixed32>(output, 2, write_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (mask_ != 0)
      ::roo_pb::WriteField<::roo_pb::Kind::kFixed32>(output, 1, mask_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  uint32_t mask_{0};
  uint32_t write_{0};
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class DataMessage_RelayResponse {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 5;

  /// Creates a message initialized to schema defaults.
  DataMessage_RelayResponse() {}

  /// Returns the current field value or its schema default.
  const uint32_t& state() const { return state_; }

  /// Assigns the field and updates explicit presence when applicable.
  void set_state(uint32_t value) { state_ = value; }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_state() { state_ = 0; }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() { clear_state(); }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const { return true; }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 1: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kFixed32)) {
            input.skip(tag);
            break;
          }
          uint32_t item{};
          ::roo_pb::ReadValue<::roo_pb::Kind::kFixed32>(input, item);
          if (input.status() != ::roo_pb::Status::kOk) return input.status();
          set_state(item);
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (state_ != 0)
      ::roo_pb::WriteField<::roo_pb::Kind::kFixed32>(output, 1, state_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  uint32_t state_{0};
};

/// Owned protobuf value; borrowed callback bindings survive Clear().
class DataMessage {
 public:
  /// Conservative encoded-size bound; SIZE_MAX means not statically bounded.
  static constexpr size_t kMaxEncodedSize = 50;

  using EnvironmentalSensorReadings =
      ::roo::comms::DataMessage_EnvironmentalSensorReadings;
  using RelayRequest = ::roo::comms::DataMessage_RelayRequest;
  using RelayResponse = ::roo::comms::DataMessage_RelayResponse;

  /// Creates a message initialized to schema defaults.
  DataMessage() {}

  /// Destroys active oneof values and their owned resources.
  ~DataMessage() { clear_contents(); }

  /// Copies owned values and borrowed callback bindings from @p other.
  DataMessage(const DataMessage& other) : DataMessage() { *this = other; }

  /// Copies values and bindings; self-assignment leaves the message unchanged.
  DataMessage& operator=(const DataMessage& other) {
    if (this == &other) return *this;
    clear_contents();
    switch (other.contents_case_) {
      case 5:
        ::new (static_cast<void*>(&environmental_sensor_readings_))::roo::
            comms::DataMessage_EnvironmentalSensorReadings(
                other.environmental_sensor_readings_);
        break;
      case 6:
        ::new (static_cast<void*>(&relay_request_))::roo::comms::
            DataMessage_RelayRequest(other.relay_request_);
        break;
      case 7:
        ::new (static_cast<void*>(&relay_response_))::roo::comms::
            DataMessage_RelayResponse(other.relay_response_);
        break;
      default:
        break;
    }
    contents_case_ = other.contents_case_;
    return *this;
  }

  /// Moves owned values and borrowed callback bindings from @p other.
  DataMessage(DataMessage&& other) noexcept : DataMessage() {
    *this = std::move(other);
  }

  /// Moves values and bindings; self-assignment leaves the message unchanged.
  DataMessage& operator=(DataMessage&& other) noexcept {
    if (this == &other) return *this;
    clear_contents();
    switch (other.contents_case_) {
      case 5:
        ::new (static_cast<void*>(&environmental_sensor_readings_))::roo::
            comms::DataMessage_EnvironmentalSensorReadings(
                std::move(other.environmental_sensor_readings_));
        break;
      case 6:
        ::new (static_cast<void*>(&relay_request_))::roo::comms::
            DataMessage_RelayRequest(std::move(other.relay_request_));
        break;
      case 7:
        ::new (static_cast<void*>(&relay_response_))::roo::comms::
            DataMessage_RelayResponse(std::move(other.relay_response_));
        break;
      default:
        break;
    }
    contents_case_ = other.contents_case_;
    return *this;
  }

  /// Identifies the active alternative in contents.
  enum class ContentsCase : uint32_t {
    kNotSet = 0,
    kEnvironmentalSensorReadings = 5,
    kRelayRequest = 6,
    kRelayResponse = 7,
  };

  /// Returns the active oneof alternative.
  ContentsCase contents_case() const {
    return static_cast<ContentsCase>(contents_case_);
  }

  /// Destroys the active value and clears selection; callback bindings survive.
  void clear_contents() {
    switch (contents_case_) {
      case 5: {
        using Value = ::roo::comms::DataMessage_EnvironmentalSensorReadings;
        environmental_sensor_readings_.~Value();
        break;
      }
      case 6: {
        using Value = ::roo::comms::DataMessage_RelayRequest;
        relay_request_.~Value();
        break;
      }
      case 7: {
        using Value = ::roo::comms::DataMessage_RelayResponse;
        relay_response_.~Value();
        break;
      }
      default:
        break;
    }
    contents_case_ = 0;
  }

  /// Returns the current field value or its schema default.
  const ::roo::comms::DataMessage_EnvironmentalSensorReadings&
  environmental_sensor_readings() const {
    if (has_environmental_sensor_readings())
      return environmental_sensor_readings_;
    static const ::roo::comms::DataMessage_EnvironmentalSensorReadings
        default_value{};
    return default_value;
  }

  /// Reports explicit field presence.
  bool has_environmental_sensor_readings() const { return contents_case_ == 5; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::DataMessage_EnvironmentalSensorReadings*
  mutable_environmental_sensor_readings() {
    if (contents_case_ != 5) {
      clear_contents();
      ::new (static_cast<void*>(&environmental_sensor_readings_))::roo::comms::
          DataMessage_EnvironmentalSensorReadings{};
      contents_case_ = 5;
    }
    return &environmental_sensor_readings_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_environmental_sensor_readings() {
    if (has_environmental_sensor_readings()) clear_contents();
  }

  /// Returns the current field value or its schema default.
  const ::roo::comms::DataMessage_RelayRequest& relay_request() const {
    if (has_relay_request()) return relay_request_;
    static const ::roo::comms::DataMessage_RelayRequest default_value{};
    return default_value;
  }

  /// Reports explicit field presence.
  bool has_relay_request() const { return contents_case_ == 6; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::DataMessage_RelayRequest* mutable_relay_request() {
    if (contents_case_ != 6) {
      clear_contents();
      ::new (static_cast<void*>(
          &relay_request_))::roo::comms::DataMessage_RelayRequest{};
      contents_case_ = 6;
    }
    return &relay_request_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_relay_request() {
    if (has_relay_request()) clear_contents();
  }

  /// Returns the current field value or its schema default.
  const ::roo::comms::DataMessage_RelayResponse& relay_response() const {
    if (has_relay_response()) return relay_response_;
    static const ::roo::comms::DataMessage_RelayResponse default_value{};
    return default_value;
  }

  /// Reports explicit field presence.
  bool has_relay_response() const { return contents_case_ == 7; }

  /// Marks the field present and returns mutable owned storage.
  ::roo::comms::DataMessage_RelayResponse* mutable_relay_response() {
    if (contents_case_ != 7) {
      clear_contents();
      ::new (static_cast<void*>(
          &relay_response_))::roo::comms::DataMessage_RelayResponse{};
      contents_case_ = 7;
    }
    return &relay_response_;
  }

  /// Restores the schema default and clears presence or repeated contents.
  void clear_relay_response() {
    if (has_relay_response()) clear_contents();
  }

  /// Restores schema defaults; callback bindings and external state survive.
  void Clear() { clear_contents(); }

  /// Checks required fields and fixed-size constraints recursively.
  bool IsInitialized() const {
    if (has_environmental_sensor_readings() &&
        !environmental_sensor_readings_.IsInitialized())
      return false;
    if (has_relay_request() && !relay_request_.IsInitialized()) return false;
    if (has_relay_response() && !relay_response_.IsInitialized()) return false;
    return true;
  }

  /// Merges one bounded message; failure leaves a valid partial value.
  ::roo_pb::Status mergeFrom(::roo_pb::Input& input) {
    while (input.status() == ::roo_pb::Status::kOk && input.remaining() != 0) {
      uint32_t tag = 0;
      if (input.tag(tag) != ::roo_pb::Status::kOk) return input.status();
      switch (tag >> 3) {
        case 5: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(
              input, *mutable_environmental_sensor_readings());
          break;
        }
        case 6: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(
              input, *mutable_relay_request());
          break;
        }
        case 7: {
          if (::roo_pb::GetWireType(tag) !=
              ::roo_pb::GetWireType(::roo_pb::Kind::kMessage)) {
            input.skip(tag);
            break;
          }
          ::roo_pb::ReadValue<::roo_pb::Kind::kMessage>(
              input, *mutable_relay_response());
          break;
        }
        default:
          input.skip(tag);
          break;
      }
    }
    return input.status();
  }

  /// Encodes resident contents; callers validate required fields separately.
  ::roo_pb::Status serialize(::roo_pb::Output& output) const {
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_relay_response())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 7,
                                                     relay_response_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_relay_request())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(output, 6, relay_request_);
    if (output.status() != ::roo_pb::Status::kOk) return output.status();
    if (has_environmental_sensor_readings())
      ::roo_pb::WriteField<::roo_pb::Kind::kMessage>(
          output, 5, environmental_sensor_readings_);
    return output.status();
  }

  /// Merges an exact borrowed byte buffer; failure leaves partial state.
  ::roo_pb::Status mergeFrom(const void* data, size_t size,
                             ::roo_pb::Limits limits = {}) {
    ::roo_pb::Input input(data, size, limits);
    return mergeFrom(input);
  }

  /// Parses and replaces contents; false indicates a protocol/resource error.
  bool ParseFromArray(const void* data, size_t size) {
    return ::roo_pb::Parse(data, size, *this) == ::roo_pb::Status::kOk;
  }

  /// Writes at the buffer start; failure can leave modified bytes.
  bool SerializeToArray(void* data, size_t capacity) const {
    size_t written = 0;
    return ::roo_pb::Serialize(*this, data, capacity, written) ==
           ::roo_pb::Status::kOk;
  }

  /// Computes encoded size; SIZE_MAX indicates callback or encoding failure.
  size_t ByteSizeLong() const {
    ::roo_pb::Output output;
    return serialize(output) == ::roo_pb::Status::kOk ? output.size()
                                                      : SIZE_MAX;
  }

 private:
  uint32_t contents_case_ = 0;
  // Only the selected alternative has a live object in this storage.
  union {
    ::roo::comms::DataMessage_EnvironmentalSensorReadings
        environmental_sensor_readings_;
    ::roo::comms::DataMessage_RelayRequest relay_request_;
    ::roo::comms::DataMessage_RelayResponse relay_response_;
  };
};

}  // namespace roo::comms
