/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "comms.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(roo_comms_DeviceDescriptor, roo_comms_DeviceDescriptor, AUTO)


PB_BIND(roo_comms_DeviceDescriptor_EnvironmentalSensor, roo_comms_DeviceDescriptor_EnvironmentalSensor, AUTO)


PB_BIND(roo_comms_DeviceDescriptor_Relay, roo_comms_DeviceDescriptor_Relay, AUTO)


PB_BIND(roo_comms_ControlMessage, roo_comms_ControlMessage, AUTO)


PB_BIND(roo_comms_ControlMessage_HubDiscoveryRequest, roo_comms_ControlMessage_HubDiscoveryRequest, AUTO)


PB_BIND(roo_comms_ControlMessage_HubDiscoveryResponse, roo_comms_ControlMessage_HubDiscoveryResponse, AUTO)


PB_BIND(roo_comms_ControlMessage_HubPairingRequest, roo_comms_ControlMessage_HubPairingRequest, AUTO)


PB_BIND(roo_comms_ControlMessage_HubPairingResponse, roo_comms_ControlMessage_HubPairingResponse, AUTO)


PB_BIND(roo_comms_DataMessage, roo_comms_DataMessage, AUTO)


PB_BIND(roo_comms_DataMessage_EnvironmentalSensorReadings, roo_comms_DataMessage_EnvironmentalSensorReadings, AUTO)


PB_BIND(roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20, roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20, AUTO)


PB_BIND(roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280, roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280, AUTO)


PB_BIND(roo_comms_DataMessage_RelayRequest, roo_comms_DataMessage_RelayRequest, AUTO)


PB_BIND(roo_comms_DataMessage_RelayResponse, roo_comms_DataMessage_RelayResponse, AUTO)





