/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_ROO_COMMS_COMMS_PB_H_INCLUDED
#define PB_ROO_COMMS_COMMS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _roo_comms_RealmId {
    roo_comms_RealmId_kUnspecifiedRealm = 0,
    roo_comms_RealmId_kHomeAutomation = 1 /* Values up to 1023 are reserved for future use.
 You can use values 1024+ for custom realms. */
} roo_comms_RealmId;

typedef enum _roo_comms_ControlMessage_HubPairingResponse_Status {
    roo_comms_ControlMessage_HubPairingResponse_Status_kOk = 0,
    roo_comms_ControlMessage_HubPairingResponse_Status_kRejected = 1
} roo_comms_ControlMessage_HubPairingResponse_Status;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(128) roo_comms_DeviceDescriptor_payload_t;
typedef struct _roo_comms_DeviceDescriptor {
    int64_t realm_id;
    roo_comms_DeviceDescriptor_payload_t payload;
} roo_comms_DeviceDescriptor;

typedef struct _roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor {
    bool has_aht20;
    bool has_bmp280;
} roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor;

typedef struct _roo_comms_HomeAutomationDeviceDescriptor_Relay {
    int32_t port_count;
} roo_comms_HomeAutomationDeviceDescriptor_Relay;

typedef struct _roo_comms_HomeAutomationDeviceDescriptor {
    pb_size_t which_kind;
    union {
        roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor environmental_sensor;
        roo_comms_HomeAutomationDeviceDescriptor_Relay relay;
    } kind;
} roo_comms_HomeAutomationDeviceDescriptor;

typedef struct _roo_comms_ControlMessage_HubDiscoveryRequest {
    bool has_device_descriptor;
    roo_comms_DeviceDescriptor device_descriptor;
} roo_comms_ControlMessage_HubDiscoveryRequest;

typedef struct _roo_comms_ControlMessage_HubDiscoveryResponse {
    uint32_t hub_channel;
} roo_comms_ControlMessage_HubDiscoveryResponse;

typedef struct _roo_comms_ControlMessage_HubPairingRequest {
    bool has_device_descriptor;
    roo_comms_DeviceDescriptor device_descriptor;
} roo_comms_ControlMessage_HubPairingRequest;

typedef struct _roo_comms_ControlMessage_HubPairingResponse {
    roo_comms_ControlMessage_HubPairingResponse_Status status;
} roo_comms_ControlMessage_HubPairingResponse;

typedef struct _roo_comms_ControlMessage {
    pb_size_t which_contents;
    union {
        roo_comms_ControlMessage_HubDiscoveryRequest hub_discovery_request;
        roo_comms_ControlMessage_HubDiscoveryResponse hub_discovery_response;
        roo_comms_ControlMessage_HubPairingRequest hub_pairing_request;
        roo_comms_ControlMessage_HubPairingResponse hub_pairing_response;
    } contents;
} roo_comms_ControlMessage;

typedef struct _roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20 {
    bool has_temperature_celsius;
    float temperature_celsius;
    bool has_humidity_percent;
    float humidity_percent;
} roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20;

typedef struct _roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280 {
    bool has_temperature_celsius;
    float temperature_celsius;
    bool has_pressure_pa;
    float pressure_pa;
} roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280;

typedef struct _roo_comms_DataMessage_EnvironmentalSensorReadings {
    bool has_generic_temperature_celcius;
    float generic_temperature_celcius;
    bool has_aht20;
    roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20 aht20;
    bool has_bmp280;
    roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280 bmp280;
} roo_comms_DataMessage_EnvironmentalSensorReadings;

typedef struct _roo_comms_DataMessage_RelayRequest {
    /* Bits that are '1' indicate relays that are to be modified to the values
 carried by corresponding `write` bits. In particular, setting mask to
 zero does not write anything (regardless of the value of `write`), and
 can be used to request state read. */
    uint32_t mask;
    uint32_t write;
} roo_comms_DataMessage_RelayRequest;

typedef struct _roo_comms_DataMessage_RelayResponse {
    /* Each bit represents the state of one relay. */
    uint32_t state;
} roo_comms_DataMessage_RelayResponse;

typedef struct _roo_comms_DataMessage {
    pb_size_t which_contents;
    union {
        roo_comms_DataMessage_EnvironmentalSensorReadings environmental_sensor_readings;
        roo_comms_DataMessage_RelayRequest relay_request;
        roo_comms_DataMessage_RelayResponse relay_response;
    } contents;
} roo_comms_DataMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _roo_comms_RealmId_MIN roo_comms_RealmId_kUnspecifiedRealm
#define _roo_comms_RealmId_MAX roo_comms_RealmId_kHomeAutomation
#define _roo_comms_RealmId_ARRAYSIZE ((roo_comms_RealmId)(roo_comms_RealmId_kHomeAutomation+1))

#define _roo_comms_ControlMessage_HubPairingResponse_Status_MIN roo_comms_ControlMessage_HubPairingResponse_Status_kOk
#define _roo_comms_ControlMessage_HubPairingResponse_Status_MAX roo_comms_ControlMessage_HubPairingResponse_Status_kRejected
#define _roo_comms_ControlMessage_HubPairingResponse_Status_ARRAYSIZE ((roo_comms_ControlMessage_HubPairingResponse_Status)(roo_comms_ControlMessage_HubPairingResponse_Status_kRejected+1))









#define roo_comms_ControlMessage_HubPairingResponse_status_ENUMTYPE roo_comms_ControlMessage_HubPairingResponse_Status








/* Initializer values for message structs */
#define roo_comms_DeviceDescriptor_init_default  {0, {0, {0}}}
#define roo_comms_HomeAutomationDeviceDescriptor_init_default {0, {roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_init_default}}
#define roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_init_default {0, 0}
#define roo_comms_HomeAutomationDeviceDescriptor_Relay_init_default {0}
#define roo_comms_ControlMessage_init_default    {0, {roo_comms_ControlMessage_HubDiscoveryRequest_init_default}}
#define roo_comms_ControlMessage_HubDiscoveryRequest_init_default {false, roo_comms_DeviceDescriptor_init_default}
#define roo_comms_ControlMessage_HubDiscoveryResponse_init_default {0}
#define roo_comms_ControlMessage_HubPairingRequest_init_default {false, roo_comms_DeviceDescriptor_init_default}
#define roo_comms_ControlMessage_HubPairingResponse_init_default {_roo_comms_ControlMessage_HubPairingResponse_Status_MIN}
#define roo_comms_DataMessage_init_default       {0, {roo_comms_DataMessage_EnvironmentalSensorReadings_init_default}}
#define roo_comms_DataMessage_EnvironmentalSensorReadings_init_default {false, 0, false, roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_init_default, false, roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_init_default}
#define roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_init_default {false, 0, false, 0}
#define roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_init_default {false, 0, false, 0}
#define roo_comms_DataMessage_RelayRequest_init_default {0, 0}
#define roo_comms_DataMessage_RelayResponse_init_default {0}
#define roo_comms_DeviceDescriptor_init_zero     {0, {0, {0}}}
#define roo_comms_HomeAutomationDeviceDescriptor_init_zero {0, {roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_init_zero}}
#define roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_init_zero {0, 0}
#define roo_comms_HomeAutomationDeviceDescriptor_Relay_init_zero {0}
#define roo_comms_ControlMessage_init_zero       {0, {roo_comms_ControlMessage_HubDiscoveryRequest_init_zero}}
#define roo_comms_ControlMessage_HubDiscoveryRequest_init_zero {false, roo_comms_DeviceDescriptor_init_zero}
#define roo_comms_ControlMessage_HubDiscoveryResponse_init_zero {0}
#define roo_comms_ControlMessage_HubPairingRequest_init_zero {false, roo_comms_DeviceDescriptor_init_zero}
#define roo_comms_ControlMessage_HubPairingResponse_init_zero {_roo_comms_ControlMessage_HubPairingResponse_Status_MIN}
#define roo_comms_DataMessage_init_zero          {0, {roo_comms_DataMessage_EnvironmentalSensorReadings_init_zero}}
#define roo_comms_DataMessage_EnvironmentalSensorReadings_init_zero {false, 0, false, roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_init_zero, false, roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_init_zero}
#define roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_init_zero {false, 0, false, 0}
#define roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_init_zero {false, 0, false, 0}
#define roo_comms_DataMessage_RelayRequest_init_zero {0, 0}
#define roo_comms_DataMessage_RelayResponse_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define roo_comms_DeviceDescriptor_realm_id_tag  1
#define roo_comms_DeviceDescriptor_payload_tag   2
#define roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_has_aht20_tag 1
#define roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_has_bmp280_tag 2
#define roo_comms_HomeAutomationDeviceDescriptor_Relay_port_count_tag 1
#define roo_comms_HomeAutomationDeviceDescriptor_environmental_sensor_tag 1
#define roo_comms_HomeAutomationDeviceDescriptor_relay_tag 2
#define roo_comms_ControlMessage_HubDiscoveryRequest_device_descriptor_tag 1
#define roo_comms_ControlMessage_HubDiscoveryResponse_hub_channel_tag 1
#define roo_comms_ControlMessage_HubPairingRequest_device_descriptor_tag 1
#define roo_comms_ControlMessage_HubPairingResponse_status_tag 1
#define roo_comms_ControlMessage_hub_discovery_request_tag 1
#define roo_comms_ControlMessage_hub_discovery_response_tag 2
#define roo_comms_ControlMessage_hub_pairing_request_tag 3
#define roo_comms_ControlMessage_hub_pairing_response_tag 4
#define roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_temperature_celsius_tag 1
#define roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_humidity_percent_tag 2
#define roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_temperature_celsius_tag 1
#define roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_pressure_pa_tag 2
#define roo_comms_DataMessage_EnvironmentalSensorReadings_generic_temperature_celcius_tag 1
#define roo_comms_DataMessage_EnvironmentalSensorReadings_aht20_tag 2
#define roo_comms_DataMessage_EnvironmentalSensorReadings_bmp280_tag 3
#define roo_comms_DataMessage_RelayRequest_mask_tag 1
#define roo_comms_DataMessage_RelayRequest_write_tag 2
#define roo_comms_DataMessage_RelayResponse_state_tag 1
#define roo_comms_DataMessage_environmental_sensor_readings_tag 5
#define roo_comms_DataMessage_relay_request_tag  6
#define roo_comms_DataMessage_relay_response_tag 7

/* Struct field encoding specification for nanopb */
#define roo_comms_DeviceDescriptor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    realm_id,          1) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           2)
#define roo_comms_DeviceDescriptor_CALLBACK NULL
#define roo_comms_DeviceDescriptor_DEFAULT NULL

#define roo_comms_HomeAutomationDeviceDescriptor_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,environmental_sensor,kind.environmental_sensor),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,relay,kind.relay),   2)
#define roo_comms_HomeAutomationDeviceDescriptor_CALLBACK NULL
#define roo_comms_HomeAutomationDeviceDescriptor_DEFAULT NULL
#define roo_comms_HomeAutomationDeviceDescriptor_kind_environmental_sensor_MSGTYPE roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor
#define roo_comms_HomeAutomationDeviceDescriptor_kind_relay_MSGTYPE roo_comms_HomeAutomationDeviceDescriptor_Relay

#define roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     has_aht20,         1) \
X(a, STATIC,   SINGULAR, BOOL,     has_bmp280,        2)
#define roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_CALLBACK NULL
#define roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_DEFAULT NULL

#define roo_comms_HomeAutomationDeviceDescriptor_Relay_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    port_count,        1)
#define roo_comms_HomeAutomationDeviceDescriptor_Relay_CALLBACK NULL
#define roo_comms_HomeAutomationDeviceDescriptor_Relay_DEFAULT NULL

#define roo_comms_ControlMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,hub_discovery_request,contents.hub_discovery_request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,hub_discovery_response,contents.hub_discovery_response),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,hub_pairing_request,contents.hub_pairing_request),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,hub_pairing_response,contents.hub_pairing_response),   4)
#define roo_comms_ControlMessage_CALLBACK NULL
#define roo_comms_ControlMessage_DEFAULT NULL
#define roo_comms_ControlMessage_contents_hub_discovery_request_MSGTYPE roo_comms_ControlMessage_HubDiscoveryRequest
#define roo_comms_ControlMessage_contents_hub_discovery_response_MSGTYPE roo_comms_ControlMessage_HubDiscoveryResponse
#define roo_comms_ControlMessage_contents_hub_pairing_request_MSGTYPE roo_comms_ControlMessage_HubPairingRequest
#define roo_comms_ControlMessage_contents_hub_pairing_response_MSGTYPE roo_comms_ControlMessage_HubPairingResponse

#define roo_comms_ControlMessage_HubDiscoveryRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_descriptor,   1)
#define roo_comms_ControlMessage_HubDiscoveryRequest_CALLBACK NULL
#define roo_comms_ControlMessage_HubDiscoveryRequest_DEFAULT NULL
#define roo_comms_ControlMessage_HubDiscoveryRequest_device_descriptor_MSGTYPE roo_comms_DeviceDescriptor

#define roo_comms_ControlMessage_HubDiscoveryResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   hub_channel,       1)
#define roo_comms_ControlMessage_HubDiscoveryResponse_CALLBACK NULL
#define roo_comms_ControlMessage_HubDiscoveryResponse_DEFAULT NULL

#define roo_comms_ControlMessage_HubPairingRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_descriptor,   1)
#define roo_comms_ControlMessage_HubPairingRequest_CALLBACK NULL
#define roo_comms_ControlMessage_HubPairingRequest_DEFAULT NULL
#define roo_comms_ControlMessage_HubPairingRequest_device_descriptor_MSGTYPE roo_comms_DeviceDescriptor

#define roo_comms_ControlMessage_HubPairingResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1)
#define roo_comms_ControlMessage_HubPairingResponse_CALLBACK NULL
#define roo_comms_ControlMessage_HubPairingResponse_DEFAULT NULL

#define roo_comms_DataMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,environmental_sensor_readings,contents.environmental_sensor_readings),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,relay_request,contents.relay_request),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (contents,relay_response,contents.relay_response),   7)
#define roo_comms_DataMessage_CALLBACK NULL
#define roo_comms_DataMessage_DEFAULT NULL
#define roo_comms_DataMessage_contents_environmental_sensor_readings_MSGTYPE roo_comms_DataMessage_EnvironmentalSensorReadings
#define roo_comms_DataMessage_contents_relay_request_MSGTYPE roo_comms_DataMessage_RelayRequest
#define roo_comms_DataMessage_contents_relay_response_MSGTYPE roo_comms_DataMessage_RelayResponse

#define roo_comms_DataMessage_EnvironmentalSensorReadings_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    generic_temperature_celcius,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  aht20,             2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  bmp280,            3)
#define roo_comms_DataMessage_EnvironmentalSensorReadings_CALLBACK NULL
#define roo_comms_DataMessage_EnvironmentalSensorReadings_DEFAULT NULL
#define roo_comms_DataMessage_EnvironmentalSensorReadings_aht20_MSGTYPE roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20
#define roo_comms_DataMessage_EnvironmentalSensorReadings_bmp280_MSGTYPE roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280

#define roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    temperature_celsius,   1) \
X(a, STATIC,   OPTIONAL, FLOAT,    humidity_percent,   2)
#define roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_CALLBACK NULL
#define roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_DEFAULT NULL

#define roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    temperature_celsius,   1) \
X(a, STATIC,   OPTIONAL, FLOAT,    pressure_pa,       2)
#define roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_CALLBACK NULL
#define roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_DEFAULT NULL

#define roo_comms_DataMessage_RelayRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  mask,              1) \
X(a, STATIC,   SINGULAR, FIXED32,  write,             2)
#define roo_comms_DataMessage_RelayRequest_CALLBACK NULL
#define roo_comms_DataMessage_RelayRequest_DEFAULT NULL

#define roo_comms_DataMessage_RelayResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  state,             1)
#define roo_comms_DataMessage_RelayResponse_CALLBACK NULL
#define roo_comms_DataMessage_RelayResponse_DEFAULT NULL

extern const pb_msgdesc_t roo_comms_DeviceDescriptor_msg;
extern const pb_msgdesc_t roo_comms_HomeAutomationDeviceDescriptor_msg;
extern const pb_msgdesc_t roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_msg;
extern const pb_msgdesc_t roo_comms_HomeAutomationDeviceDescriptor_Relay_msg;
extern const pb_msgdesc_t roo_comms_ControlMessage_msg;
extern const pb_msgdesc_t roo_comms_ControlMessage_HubDiscoveryRequest_msg;
extern const pb_msgdesc_t roo_comms_ControlMessage_HubDiscoveryResponse_msg;
extern const pb_msgdesc_t roo_comms_ControlMessage_HubPairingRequest_msg;
extern const pb_msgdesc_t roo_comms_ControlMessage_HubPairingResponse_msg;
extern const pb_msgdesc_t roo_comms_DataMessage_msg;
extern const pb_msgdesc_t roo_comms_DataMessage_EnvironmentalSensorReadings_msg;
extern const pb_msgdesc_t roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_msg;
extern const pb_msgdesc_t roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_msg;
extern const pb_msgdesc_t roo_comms_DataMessage_RelayRequest_msg;
extern const pb_msgdesc_t roo_comms_DataMessage_RelayResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define roo_comms_DeviceDescriptor_fields &roo_comms_DeviceDescriptor_msg
#define roo_comms_HomeAutomationDeviceDescriptor_fields &roo_comms_HomeAutomationDeviceDescriptor_msg
#define roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_fields &roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_msg
#define roo_comms_HomeAutomationDeviceDescriptor_Relay_fields &roo_comms_HomeAutomationDeviceDescriptor_Relay_msg
#define roo_comms_ControlMessage_fields &roo_comms_ControlMessage_msg
#define roo_comms_ControlMessage_HubDiscoveryRequest_fields &roo_comms_ControlMessage_HubDiscoveryRequest_msg
#define roo_comms_ControlMessage_HubDiscoveryResponse_fields &roo_comms_ControlMessage_HubDiscoveryResponse_msg
#define roo_comms_ControlMessage_HubPairingRequest_fields &roo_comms_ControlMessage_HubPairingRequest_msg
#define roo_comms_ControlMessage_HubPairingResponse_fields &roo_comms_ControlMessage_HubPairingResponse_msg
#define roo_comms_DataMessage_fields &roo_comms_DataMessage_msg
#define roo_comms_DataMessage_EnvironmentalSensorReadings_fields &roo_comms_DataMessage_EnvironmentalSensorReadings_msg
#define roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_fields &roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_msg
#define roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_fields &roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_msg
#define roo_comms_DataMessage_RelayRequest_fields &roo_comms_DataMessage_RelayRequest_msg
#define roo_comms_DataMessage_RelayResponse_fields &roo_comms_DataMessage_RelayResponse_msg

/* Maximum encoded size of messages (where known) */
#define ROO_COMMS_COMMS_PB_H_MAX_SIZE            roo_comms_ControlMessage_size
#define roo_comms_ControlMessage_HubDiscoveryRequest_size 145
#define roo_comms_ControlMessage_HubDiscoveryResponse_size 6
#define roo_comms_ControlMessage_HubPairingRequest_size 145
#define roo_comms_ControlMessage_HubPairingResponse_size 2
#define roo_comms_ControlMessage_size            148
#define roo_comms_DataMessage_EnvironmentalSensorReadings_AHT20_size 10
#define roo_comms_DataMessage_EnvironmentalSensorReadings_BMP280_size 10
#define roo_comms_DataMessage_EnvironmentalSensorReadings_size 29
#define roo_comms_DataMessage_RelayRequest_size  10
#define roo_comms_DataMessage_RelayResponse_size 5
#define roo_comms_DataMessage_size               31
#define roo_comms_DeviceDescriptor_size          142
#define roo_comms_HomeAutomationDeviceDescriptor_EnvironmentalSensor_size 4
#define roo_comms_HomeAutomationDeviceDescriptor_Relay_size 11
#define roo_comms_HomeAutomationDeviceDescriptor_size 13

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
